### ISSUE TITLE
Google Font not loading

### ISSUE THREAD

**Issue by deadlyraptor** [deadlyraptor/reels-app#1]
The correct code is in there but for some reason, neither Chrome nor Firefox loads the font.

HTML
```html
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
```

CSS
```css
body {
    font-family: 'Lato', sans-serif;
}
```
